= REST API Guide
HUNGRY-BROTHERS;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 때 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[overview-error-codes]]
== 에러 코드

에러 코드 목록입니다.

|===
| 상태 코드 | 에러 코드 | 메시지

| 400
| C001
| 잘못된 요청입니다. 관리자에게 문의하세요.

| 405
| C002
| 비정상 요청입니다. 관리자에게 문의하세요.

| 400
| C003
| 요청하신 사항을 찾을 수 없습니다.

| 500
| C004
| 서버 오류입니다. 관리자에게 문의하세요.

| 400
| C005
| 잘못된 요청입니다. 관리자에게 문의하세요.

| 403
| C006
| 권한이 없습니다. 관리자에게 문의하세요.

| 401
| C007
| 인증 토큰이 만료되었습니다. 다시 로그인 해주세요.

| 400
| C008
| 이메일 주소가 유효하지 않습니다. 이메일 주소를 확인해주세요.

| 400
| C009
| 인증 코드가 유효하지 않습니다. 인증 코드를 확인해주세요.

| 400
| C010
| 이미 존재하는 아이디입니다. 이메일을 확인해주세요.
|===

[[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다.
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다.
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 한다.

[[resources]]
= 리소스

[[resources-sign]]
== 회원

[[resources-sign-up]]
=== 회원 가입

`POST` 요청을 사용해서 회원 가입을 할 수 있다.

operation::sign-up[snippets='http-request,http-response']

[[resources-sign-up-invalid]]
=== 회원 가입 - 아이디, 닉네임, 비밀번호가 유효하지 않은 경우

회원 가입은 이메일, 닉네임, 비밀번호 형식에 맞는 값으로 해야 한다.

operation::sign-up-invalid[snippets='http-request,http-response']

[[resources-sign-in]]
=== 로그인

`POST` 요청을 사용해서 로그인을 할 수 있다.

operation::sign-in[snippets='http-request,http-response']

[[resources-sign-refresh-token]]
=== 토큰 갱신

`POST` 요청을 사용해서 토큰을 갱신할 수 있다.

operation::refresh-token[snippets='http-request,http-response']

[[resources-sign-send-email]]
=== 이메일 전송

`POST` 요청을 사용해서 인증 번호를 포함한 이메일을 보낼 수 있다.

operation::send-email[snippets='http-request,http-response']

[[resources-sign-verify-email]]
=== 이메일 검증

`PATCH` 요청을 사용해서 이메일을 검증할 수 있다.

operation::verify-email[snippets='http-request,http-response']


[[resources-subscriptions]]
== 구독 정보

[[resources-subscription-read]]
=== 하나의 구독 정보 조회 성공

`GET` 요청을 사용해서 하나의 구독 정보를 조회할 수 있다.

operation::read-subscription[snippets='http-request,http-response']

[[resources-subscriptions-read]]
=== 구독 정보 리스트 조회 성공

`GET` 요청을 사용해서 구독 정보 리스트를 조회할 수 있다.

operation::read-subscriptions[snippets='http-request,http-response']

[[resources-subscription-create]]
=== 하나의 구독 정보 생성 성공

`POST` 요청을 사용해서 하나의 구독 정보를 생성할 수 있다.

operation::create-subscription[snippets='http-request,http-response']

[[resources-subscription-update]]
=== 하나의 구독 정보 수정 성공

`PATCH` 요청을 사용해서 하나의 구독 정보를 수정할 수 있다.

operation::update-subscription[snippets='http-request,http-response']

[[resources-subscription-delete]]
=== 하나의 구독 정보 삭제 성공

`DELETE` 요청을 사용해서 하나의 구독 정보를 삭제할 수 있다.

operation::delete-subscription[snippets='http-request,http-response']
